services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.django
    container_name: django
    restart: always
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 10s
      timeout: 5s
      retries: 30     
    networks:
      - app-network



  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - celery
    volumes:
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network


  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: celery
    restart: always
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - django
      - redis
    networks:
      - app-network
      

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network


  db:
    image: postgres:15
    container_name: db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - app-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=inshopping
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge